SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d')  # DATE_FORMAT을 사용해서 출판일 리스트 출력
AS PUBLISHED_DATE
FROM BOOK AS b
JOIN AUTHOR AS a ON b.AUTHOR_ID = a.AUTHOR_ID #join을 사용해서 
WHERE CATEGORY = '경제' 
ORDER BY PUBLISHED_DATE ASC;
